### ISSUE TITLE
Make editable Preset descriptions more obvious

### ISSUE THREAD

**Issue by andybluenoes** [tappi287/rf2_video_settings#1]
When i hover over my presets on the dashboard, they all have the same message tooltip like the attached
Many thanks
Andy
<img width="626" alt="Capture" src="https://user-images.githubusercontent.com/60150948/109368663-c1af1500-7891-11eb-9035-739a8cfcd029.PNG">

**Comment by tappi287** [comment]
Hi Andy, cheers for taking the time to post feedback! The tooltip is displaying the preset description which you can edit in the Graphics tab.

But I understand that the current behaviour of copying the description from the selected preset whenever you create a new one is unintuitive. I'll change the beaviour so every new preset will start with a blank description. This way it would also be more obvious that the description is editable.

**Comment by andybluenoes** [comment]
Ah, I see it now, I didnt realise where that description comes from. Make sense now, I just didnt see it before!
I dont know if its an rf2 fault as a lot of bugs at the moment, but the server browser doesnt seem to indicate the number of live people on, only AI.

**Comment by tappi287** [comment]
Regarding the player numbers: that is not a bug on either side. Just the Steam legacy master server not getting regular updates with player data from the dedicated server instances. rF2 will acquire this info on it's "own", without using the steamp api if I understand it correctly. I do not have any documentation how rF2 is doing it and therefore can only use the Steam Api with very outdated player/bot data.

**Comment by andybluenoes** [comment]
Understand, thanks Stefan.
Great work with this app, saves so much time trying to get the best gfx settings in VR
