### ISSUE TITLE
Critical Error rF2 Settings Widget 1.4.3

### ISSUE THREAD

**Issue by dubfl0w** [tappi287/rf2_video_settings#12]
Hello, I installed the update and for the first run it was fine. After a restart I get this message and can not start the app any longer

An error occurred trying to read settings:
Could not read player.JSON file! Expecting property name enclosed in double quotes: line 837 column 3 (char 50226)
Could not read player.JSON file! Expecting property name enclosed in double quotes: line 837 column 3 (char 50226)
Could not read rFactor2 settings for AdvancedGraphicSettings

I haven't changed the UAC or anything?

**Comment by tappi287** [comment]
Hey, thanks for the report. Your player.Json is corrupted then. If you can
start rF2 and everything works then it would be the app. In that case I'd
need the player.json file to have a look at that.

dubfl0w ***@***.***> schrieb am Di., 8. Nov. 2022, 12:54:

**Comment by dubfl0w** [comment]
Hello, yes it was my fault. I deleted some lines so that they get re-created when launching the game. But it created the conflict with the widget. I launched the game from steam and than it works now. Thank you
