### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by jojopelfort** [tappi287/rf2_video_settings#14]
Hello,
I have a problem with this application. When I start it, sht stays in the task manager but no windows open. It's the same problem with all version. I have been looking for some time but no results.
Does anyone have  any idea about this problem?
Thanks you in advance.

**Comment by tappi287** [comment]
Can you take a look if you find a ..exception.log under `%localappdata%\rf2_settings_widget`? +please use netstat to find any other software on your machine listening at port 8123. This port is needed for the app to run.

**Comment by jojopelfort** [comment]
It is the only file that i had find under %localappdata%\rf2_settings_widget 
 [rf2_settings_widget.log](https://github.com/tappi287/rf2_video_settings/files/10407069/rf2_settings_widget.log)
No port 8123 used by any other software.

**Comment by tappi287** [comment]
It should work if you make the path `C:\\Users\\Jojopelfort\\Documents\\rf2_settings_widget` accessible and writeable.

**Comment by jojopelfort** [comment]
I had already tested it this week end and I reach the same result.
Same thing on an other account from my pc. 
[rf2_settings_widget.log](https://github.com/tappi287/rf2_video_settings/files/10439720/rf2_settings_widget.log)

**Comment by jojopelfort** [comment]
Hello,
I  just found the problem of starting the application. You must have chrome installed. until today I was using only opera. After having installed chrome, rf2 widget has started normaly. 
Thanks you for your help

**Comment by tappi287** [comment]
Hmm, it should launch in Edge when Chrome isn't available. I'll take a look whenever I find the time. Thanks for the report!

**Comment by jojopelfort** [comment]
Hello,
I just try again to launch the soft after delete chrome and it is ok. Now rf2 widget starts with opera software.
Good job and thanks you.
Bye-bye

**Comment by tappi287** [comment]
Thanks for reporting back!
