### ISSUE TITLE
Launch in VR

### ISSUE THREAD

**Issue by Bean789789** [tappi287/rf2_video_settings#15]
Hi - loving the widget, been using it for several months with Oculus Quest 2.

Recent rF2 upgrade however means that the widget seems to refuse to launch in VR mode, like it used to everytime before.  I use OpenXR and have replaced the openvr_api.dll in Bin64 but that doesn't fix it.  Any ideas?

Thanks!

**Comment by tappi287** [comment]
Thanks for the report. It just starts rf2 binary without any special commands. Are you sure it starts in VR if you directly start the executable?

**Comment by Bean789789** [comment]
If I start it from Steam, it works fine.  Just looked at the patch notes - could this be a reason...?

Client: 10601581

Dedicated Server: 10601594

General

-  Track Limits: reduced sensitivity to switching paths, such as near the pit lane entrance, and reduced strict penalty points for an invalid pit lane to main path change from Drive Through to 1 point.
-  Vehicle option for brake repair in a pitstop
- **Added “+VR” command line option to launch the game using VR. Added new steam option when starting game.**

**Comment by delzimar** [comment]
Same problem here

> Olá, adorei o widget, estou usando-o há vários meses com o Oculus Quest 2.
> 
> A atualização recente do rF2, no entanto, significa que o widget parece se recusar a iniciar no modo VR, como costumava fazer antes. Eu uso o OpenXR e substituí o openvr_api.dll no Bin64, mas isso não resolve. Alguma ideia?
> 
> Obrigado!

**Comment by delzimar** [comment]
> Hi - loving the widget, been using it for several months with Oculus Quest 2.
> 
> Recent rF2 upgrade however means that the widget seems to refuse to launch in VR mode, like it used to everytime before. I use OpenXR and have replaced the openvr_api.dll in Bin64 but that doesn't fix it. Any ideas?
> 
> Thanks!

Same problem here.

**Comment by tappi287** [comment]
Please take a look if the latest version works for you https://github.com/tappi287/rf2_video_settings/releases/tag/1.4.4 and report back if it does not.

**Comment by Bean789789** [comment]
Thanks Tappi - seems to work fine.  Much appreciate the work to update the code. Thank you.

Question - does the setting widget just write a 'settings' file which would be used if I just initiated the exe direct, or does it inject those settings, or dynamically create that file, as I start rF2 from the widget?  Thanks!

**Comment by tappi287** [comment]
It writes to the player.json, controller.json, dx_config.ini and ReShade presets(when in use) and afterwards starts rF2 with the option you choose. This means you can manipulate settings however you like in the widget and start rF2 from wherever you want afterwards.

**Comment by delzimar** [comment]
> It writes to the player.json, controller.json, dx_config.ini and ReShade presets(when in use) and afterwards starts rF2 with the option you choose. This means you can manipulate settings however you like in the widget and start rF2 from wherever you want afterwards.

Thank you very much, this app is essential for anyone who wants to switch between monitors and VR. great job

**Comment by delzimar** [comment]
The first time the option appeared to be able to select the execution by steam or .exe of the game. Then it starts directly without being able to choose again. There's a way to leave it as before. choosing VR starts on VR choosing HIGH starts on monitor?

**Comment by tappi287** [comment]
Just use the drop down menu(arrow on the right) next to the launch button to select a different launch option.

**Comment by tappi287** [comment]
> There's a way to leave it as before. choosing VR starts on VR choosing HIGH starts on monitor?

Nope, they've taken that option away from us with those new launch options :/

**Comment by tappi287** [comment]
* Note to myself: implement a VR/pancake switch [x] per Graphics Preset.

**Comment by delzimar** [comment]
> 

after I started it once in VR , the other settings only work in VR too, that is, I can no longer start it from the monitor using the app

**Comment by tappi287** [comment]
> > 
> 
> after I started it once in VR , the other settings only work in VR too, that is, I can no longer start it from the monitor using the app

See https://github.com/tappi287/rf2_video_settings/issues/15#issuecomment-1445832451_

**Comment by tappi287** [comment]
..and yes I will have to implement a VR/pancake switch inside the Graphics Preset to "restore" the old behaviour of having presets either starting in VR or pancake.

**Comment by delzimar** [comment]
> and yes I will have to implement a VR/pancake switch inside the Graphics Preset to "restore" the old behaviour of having presets either starting in VR or pancake.

Ok, Thank you

**Comment by tappi287** [comment]
This has been adressed:
github.com/tappi287/rf2_video_settings/releases/latest
