### ISSUE TITLE
Benchmark - launch in VR

### ISSUE THREAD

**Issue by justposted** [tappi287/rf2_video_settings#16]
Hello. Although launching into VR works nicely, it isn't working for benchmarks. I've even set the +VR flag in Steam myself, but it still starts in pancake mode if I hit the Start Benchmark Queue button.

Thanks for updating your invaluable widget for the new release and for doing it so quickly. Your efforts are much appreciated.

**Comment by tappi287** [comment]
Hi, thanks for the report. I'd have to implement a UI element letting you choose VR/pancake for the benchmark but I'm afraid I won't find the time within the next 2 weeks.

**Comment by tappi287** [comment]
THis has been adressed:
github.com/tappi287/rf2_video_settings/releases/latest
