### ISSUE TITLE
grainspread.fx failed to compile

### ISSUE THREAD

**Issue by escknx** [tappi287/rf2_video_settings#18]
grainspread.fx failed to compile in reshade console and as a result reshade preset does not work
portable version win10
screenshot is attached
![screen](https://github.com/tappi287/rf2_video_settings/assets/53890365/8d8be518-87e1-4245-9ba1-2b74989c6969)

**Comment by tappi287** [comment]
None of the shaders listed in the screenshot are part of this app. You can delete the Reshade directory in your rF2/Bin64 directory and let the widget handle the install or follow the onscreen instruction to fix errors in your own ReShade installation.
