### ISSUE TITLE
Favorite Steam links to join Server

### ISSUE THREAD

**Issue by fiR3b0ll** [tappi287/rf2_video_settings#19]
Nice tool!
But i can´t use it for the league races. In our league we have a url link (steam://rungameid....) with the server datas.
I can´t join the game over the tool and i have terrible fps with my vr.

**Comment by tappi287** [comment]
Hey, thanks, supporting custom urls seems like a good idea. I'll take a look if I find the time.

**Comment by tappi287** [comment]
You can try this now with this release: https://github.com/tappi287/rf2_video_settings/releases/tag/1.5.0
