### ISSUE TITLE
SUggestion

### ISSUE THREAD

**Issue by andybluenoes** [tappi287/rf2_video_settings#2]
Hi there
Just wondering if it would be possible to have some additional launch options available.
I use crew chief and sumhub, it would be great if there was an option to add launch buttons for external programs like that. Not sure its possible, but thought I would ask.
Andy

**Comment by tappi287** [comment]
Hey, thanks for the suggestion. I think this is a little out of scope as there are extra win32 librarys required to efficently detect running processes and I would like to keep the footprint of the app as small as possible.
For what you describe, you can use [SimMon](https://github.com/tappi287/simmon_gui). Just install the background watcher and use the "SimRacing" profile and you're ready to go. SimHub and CrewChief will start whenever rf2 is launched.

**Comment by andybluenoes** [comment]
Thanks, I will have a look at SimMon, looks useful :-)
