### ISSUE TITLE
Malware Detection

### ISSUE THREAD

**Issue by XpectoPetroleum** [tappi287/rf2_video_settings#21]
Hi,

I went to download your widget however avast believes there is a trojan horse in the executable. Is your compiled version infected?

Cheers.

**Comment by tappi287** [comment]
The latest release has more than 1,5k Downloads so I doubt that there is something malicious inside:
https://somsubhra.github.io/github-release-stats/?username=tappi287&repository=rf2_video_settings

For the false positives with the software used to create the binary, see a detailed explanation here:
https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/antivirus.md

**Comment by tappi287** [comment]
Btw, this is a new release which might not trigger you AV Software:
https://github.com/tappi287/rf2_video_settings/releases/tag/1.5.4

**Comment by XpectoPetroleum** [comment]
Hi. Thanks for updating the project. It now behaves differently with Avast. Previously the exe version would download but Avast would stop it executing, and the portable version wouldn't finish downloading as Avast stopped it before it would complete.  Now, they both download fine and when I manually scan them all is OK, however when executing they get stopped and get sent to their servers for a deep analysis.
