### ISSUE TITLE
RF2 RC update

### ISSUE THREAD

**Issue by andybluenoes** [tappi287/rf2_video_settings#3]
Hi Tappi

Just a quick note, it looks like due to the change in the latest RC of RF2, the video settings option has change to MSAA rather than whatever it was before, and this doesnt get saved in each different profile you make.

Also, the environment reflection doesnt seem to change in game if you change it in a profile, not sure if that was the case before todays rf2 update as I never really noticed it.

Cheers

**Comment by tappi287** [comment]
Hey Andy, thanks for the hint! I had already implemented the MSAA setting yesterday and you can try out a release candidate if you want:
[rF2_Settings_Wizard_0.9.5rc](https://github.com/tappi287/rf2_video_settings/releases/tag/0.9.5rc)
Note that the rf2 Auto Headlight feature kind of breaks the headlight feature for now.

Could you investigate which player JSON setting is affected by the env reflection and maybe which value corresponds to which setting? The widget changes the player.JSON setting with the key ['Environment Reflections'](https://github.com/tappi287/rf2_video_settings/blob/32e23bdfeb2ccc921fa69dfb30717abeda692a95/rf2settings/settingsdef/graphics.py#L76)

**Comment by andybluenoes** [comment]
Hi Stefan
I should of realised you would already be on the case :-)
Ive jsut tried the RC, but for me, its not saving the change in MSAA at all now for some reason.
I checked the configdx11.ini where I think that setting is saved and it doesnt  change 


I think i can see the problem with the environment reflections.
There are more levels of adjustment available in the game than in the app, The app has off (0), low (1) and high (2), the game goes off (0), low (1), medium (2), high (3) and ultra (4), so it looks like the app doesnt allow the game to set higher than medium

When changing in game and monitoring the player.json file changes here, its line 377 on my player.json:
 "Environment Reflections":0,

Hope that helps
Andy

**Comment by andybluenoes** [comment]
I jsut found something interesting, I might be looking at the wrong thing, but in the json files that are created for your graphics profiles, it looks like the MSAA key doesnt get updated when you make changes using rfconfig via the app.
Im guessing that that gets pushed into the dx11config file...but i may be completely wrong
