### ISSUE TITLE
RC Screen Space Reflection (SSR)

### ISSUE THREAD

**Issue by andybluenoes** [tappi287/rf2_video_settings#4]
Hi Stefan
Maybe you are waiting for each RC to go into full release before including everything, but you may know there is also an option for Screen Space Reflection (SSR) level within gfx config.

Be nice if you could build that into the settings available.

No major thing for the moment though ;-)

**Comment by tappi287** [comment]
Hey Andy, thanks for the hint! I thought it's a little early to add that. I'm pretty sure they will add and/or refine the settings quite a lot until the next stable build. I guess other Screen Space calculated features are not that far aswell(e.g. SSAO).

**Comment by andybluenoes** [comment]
Makes perfect sense, going to be interesting to see how all these new things work, and what sort of impact they will have on comfortably running it in Vr ;-)
