### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by andybluenoes** [tappi287/rf2_video_settings#5]
![Capture](https://user-images.githubusercontent.com/60150948/121887273-6e60b580-cd0e-11eb-875d-c7585daf66ad.JPG)

Receiving the error message attached starting the app.

I have managed to get passed it by restoring a previous copy of my player.json, but it seems to happen every now and again, maybe when something is changed in game?

**Comment by andybluenoes** [comment]
I notice that when comparing the two files in notepad++ I get a prompt saying that the encoding is different in the two files.

**Comment by tappi287** [comment]
Can you try the new release and see if that is fixed?
https://github.com/tappi287/rf2_video_settings/releases/download/0.9.81/rF2_Settings_Wizard_0.9.81_win64.exe

**Comment by andybluenoes** [comment]
Will do, thanks, just installed it, will try it out the next couple of days.

**Comment by andybluenoes** [comment]
All seems fine now, couple of nights, also changing my settings a few times, and no issues :-)

**Comment by tappi287** [comment]
Nice! Thanks for testing it Andy! The game dynamically encodes the Json based on the characters used.
