### ISSUE TITLE
Headlight operation changed in the game

### ISSUE THREAD

**Issue by TonyWhitley** [tappi287/rf2_video_settings#6]
See https://github.com/TonyWhitley/rF2headlights/issues/3 and the change https://github.com/TonyWhitley/rF2headlights/commit/8b76ac4fe705432e641efa4dad4af5e07fe666c8

**Comment by tappi287** [comment]
Thanks for the hint Tony! I'll have a look soon™️  ..and welcome back to your coding Mojo :)

**Comment by tappi287** [comment]
fixed in https://github.com/tappi287/rf2_video_settings/commit/15548eb274894eb0e8ee72c86c2a43cbed0770e4
