### ISSUE TITLE
no tab to show lan servers

### ISSUE THREAD

**Issue by hany3** [tappi287/rf2_video_settings#7]

**Comment by tappi287** [comment]
If you have hints how to implement this from outside the game, I'm listening

**Comment by hany3** [comment]
Sorry for the late reply, I was about to send you a request to implement lan server functionality in your launcher, but just released that I already created this thread a while ago.  To create LAN server for rFactor 2 from within the dedicated server, it uses the exact same process with creating an internet server but with using different port numbers as follows

- WebUI port: it uses port 5398 (LAN), instead of port 5397 (internet)
- http server port: it uses port 27013 (LAN), instead of port 64297 (internet)
- Simulation port: it uses port 17013 (LAN), instead of port 54297 (internet)

So it is a matter of changing port numbers, using these ports number will force the game to create a lan server instead of an internet server. 

I also suggest that you change the name of the tool from rf2 video setting to rf2 Launcher or something broader since it does too many things not just the video settings, thank you very much for the great tool.

**Comment by tappi287** [comment]
Hey, thanks for the info, I'd still have no starting point where to pull information from the network to list LAN servers.

**Comment by hany3** [comment]
I can confirm LAN server functionality is working as it should be in the new version 1.5.0.  I tested it on 2 different PCs, including the one that is actually hosting the server. I just used the new tab to add the LAN server with its local network IP address **192.168.1.x** and the port number **27013**, and the game connected to the LAN server in seconds. You tool is by far the best tool ever made for rfactor 2 in 10 years. Thank you for implementing this function.  Next functionality may be to add a LAN server lookup/browse function to search function for LAN servers within local network and obtain LAN server information (like track name, cars, etc,,) similar to looking up other online servers but this is not a big deal. 

BTW I changed in game install path within steam to a different drive and was not able to find any option in the rf2_settings_widget to manually select the install path of rfactor 2. After multiple restarts of both the game and the widget it could auto-detect the new game install location within steam. It would be great if you add an option in the general settings to manually choose the game install location after the initial widget setup because this option is only available on initial setup of the widget and if you change the game location later on, there is no option to do this manually and you have to wait until it  automatically detects the install location within steam. 

Thanks again for the adding the LAN server functionality and waiting for LAN server lookup/browser and an option to change the game location in the next versions.

**Comment by tappi287** [comment]
Hey, thanks for the feedback and test runs! Mid term I won't find the time to implement and maintain such a LAN look up feature.

The installation location can only be detected if the game was at least started once at the new location. Btw, there is no initial setup to set the game location. It is always auto detected via Steam files. However I've added the location overwrite input to the preferences page so people with older Steam installations or unexpected setups can set an overwrite. Next release will have hat included.
