### ISSUE TITLE
No FSR - NIS option available. 

### ISSUE THREAD

**Issue by balamacab** [tappi287/rf2_video_settings#8]
There's a tool to improve even better the VR performance in rFactor2 (or almost any OpenVR game), Open Fsr (https://github.com/fholger/openvr_fsr)
Given that's a dll and a config file if can be easily integrated to this wonderful tool, and improve the performance in VR even further.

**Comment by tappi287** [comment]
"Easily" is a bold claim ;P But here you go:
[latest release](https://github.com/tappi287/rf2_video_settings/releases/latest)
